### ISSUE TITLE
Suggestion: Use inline and crossinline

### ISSUE THREAD

**Issue by lozierkyle** [KucherenkoIhor/CompositionOfFunctionsInKotlin#1]
This will cut down on the number of anonymous classes after compilation

**Comment by KucherenkoIhor** [comment]
Hi @lozierkyle,
So you suggest to add inline for plus operator and crossinline for argument, right?
I tried this approach, and it didn't cut down the number of anonymous classes. 
Please try this and if it works as you suggest please share code with me

**Comment by lozierkyle** [comment]
@KucherenkoIhor if you check the decompiled Java, you will notice no difference since `inline` is a compiler instruction. I included two images of a demonstration I put together. The first one is your version with 20 method references (7 + 7 + 4 + 2). The latter is inlined with only 15 method references (7 + 4 + 2 + 2). Unfortunately, this does not demonstrate the cutting down of anonymous classes, but I hope you can still see the benefit
![notinlined](https://user-images.githubusercontent.com/7979801/36038474-b4d2eb1c-0d74-11e8-9464-03f4d1811afb.png)
![inlined](https://user-images.githubusercontent.com/7979801/36038469-b20c265a-0d74-11e8-8bfc-8a85106d12f6.png)

**Comment by KucherenkoIhor** [comment]
@lozierkyle https://github.com/KucherenkoIhor/CompositionOfFunctionsInKotlin#changelog

**Comment by KucherenkoIhor** [comment]
@lozierkyle Thank you!!
